#!/bin/sh

# Gets battery level and check if it's charging
bat_level=$(acpi -b | grep -o '[0-9]*%')
bat_level=${bat_level%?}
charging=$(acpi -b | grep -o 'Charging\|Unknown\|Full')

if [ $charging = "Charging" ] || [ $charging = "Unknown" ]; then
    echo "<fc=#494D76>chg</fc> $bat_level%"
elif [ $bat_level -le "15" ]; then
    echo "<fc=#494D76>bat</fc> <fc=#489E9E>$bat_level</fc>%"
else
    echo "<fc=#494D76>bat</fc> $bat_level%"
fi

exit 0
