#!/bin/sh

# Gets master volume info
vol=$(amixer get Master | awk -F'[]%[]' '/%/ {if ($7 == "off") { print "x" } else { print $2 }}' | head -n 1)

if [ $vol = "x" ]; then
    echo "<fc=#7878D1> </fc>x"
elif [ $vol = "0" ]; then
    echo "<fc=#7878D1> </fc>$vol%"
else
    echo "<fc=#7878D1> </fc>$vol%"
fi

exit 0
