#!/bin/bash

# Specifying the icon(s) in the script
# This allows us to change its appearance conditionally
icon=" "

pgrep -x redshift &> /dev/null
if [[ $? -eq 0 ]]; then
    temp=$(redshift -p 2>/dev/null | grep temp | cut -d' ' -f3)
    temp=${temp//K/}
fi

# OPTIONAL: Append ' ${temp}K' after $icon
if [[ -z $temp ]]; then
    #echo "%{F#65737E}$icon"       # Greyed out (not running)
    echo "<fc=#B0B8B7>$icon</fc>"
elif [[ $temp -ge 5000 ]]; then
    #echo "%{F#8FA1B3}$icon"       # Blue
    echo "<fc=#A5A5A5>$icon</fc>"
elif [[ $temp -ge 4200 ]]; then
    echo "<fc=#9A7848>$icon</fc>"       # Yellow
else
    echo "<fc=#9A4B48>$icon</fc>"       # Red
fi
