#!/bin/sh

# Sets the background wallpaper (tiled)
[ ! -z "$1" ] && cp "$1" ~/Images/Wallpapers/current-thinkpad.png && notify-send -i "$HOME/Images/Wallpapers/current-thinkpad.png" "Wallpaper changed."
feh --bg-tile ~/Images/Wallpapers/current-thinkpad.png
